name: Deploy to Play With Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to PWD node
        run: |
          scp docker-compose.yml index.html ip172-18-0-74-d0ncmki91nsg00afualg@direct.labs.play-with-docker.com:~

      - name: Deploy via Docker Compose
        run: |
            docker compose down || true
            docker compose up -d
